### ISSUE TITLE
Customize the video save url for deep AR instance

### ISSUE THREAD

**Issue by Zulqurnain24** [DeepARSDK/quickstart-ios-swift#10]
Usually this is the way we set the parameters for the deepAR instance. Can we customize the video save url path or with some other approach?

" let videoQuality = 0.1
let bitrate = 1250000
let frame = 30
let videoSettings:[AnyHashable : AnyObject] = [
AVVideoQualityKey : (videoQuality as AnyObject),
AVVideoAverageBitRateKey : (bitrate as AnyObject),
AVVideoExpectedSourceFrameRateKey : (frame as AnyObject)
]

let rect = CGRect(x: (isSolo ? 0.0 : 0.15), y: 0, width: (isSolo ? 1.0 : 0.5), height: 1)

deepAR?.startVideoRecording(withOutputWidth: width, outputHeight: height, subframe: rect, videoCompressionProperties: videoSettings, recordAudio: true)"

Thanks in advance

**Comment by JelenaKB** [comment]
Sorry, the video save URL can't be changed at this time. We will look into it.

**Comment by igor-aradski** [comment]
This is now possible with the functions [`setVideoRecordingOutputName`](https://docs.deepar.ai/deepar-sdk/deep-ar-sdk-for-ios/api-reference/documentation/deepar/deepar/setvideorecordingoutputname(_:)) and [`setVideoRecordingOutputPath`](https://docs.deepar.ai/deepar-sdk/deep-ar-sdk-for-ios/api-reference/documentation/deepar/deepar/setvideorecordingoutputpath(_:)).
