### ISSUE TITLE
[BUG] faceTracked(_ faceData: MultiFaceData) is always executed

### ISSUE THREAD

**Issue by olegkhomenko** [DeepARSDK/quickstart-ios-swift#15]
Hi, 

If define `faceTracked` in `ViewController` in the default `quickstart-ios-swift` project
```swift
extension ViewController: DeepARDelegate {
    func faceTracked(_ faceData: MultiFaceData) {
        print("Face Tracked")
    }
}
```
__This method is always executed__, even if there is no person in the camera (see. screenshot)
It looks like it's wrong behavior according to documentation:
> ...
> __(void)faceTracked:(MultiFaceData)faceData__
> Called on each frame where at least one face data is detected.
> ...

__Screenshot example (faceTracked is executed on this frame)__
<img src=https://user-images.githubusercontent.com/7049767/103080041-17431900-45e6-11eb-9474-cb5d2343b9e0.jpeg width=200px>

**Comment by JelenaKB** [comment]
Thank you for bringing this to our attention. This is a documentation issue,`(void)faceTracked:(MultiFaceData)faceData` should be called whenever face tracking processes a frame, whether or not a face is visible. We will fix this in our docs. 

If you need to know if a face is visible, you should check `faceData[i].faceVisible` for all faces, or use 
`(void)faceVisiblityDidChange:(BOOL)faceVisible`
