### ISSUE TITLE
feature request - expose some studio controls in SDK

### ISSUE THREAD

**Issue by buabbud** [DeepARSDK/quickstart-ios-swift#20]
Hello,

I'm creating a morph filter which morphs specific facial features individually (eyes, nose, mouth, etc.). In DeepAR studio, I can select each individual "Blend Shape", and adjust the weight of the specific feature (for example, to make the eyes larger and nose smaller). I would like to extend this capability to my end users. I would like to propose a feature in your SDK (iOS please :)) that recognizes and exposes specific blend shapes in a .fbx and allows the developer to input the weight of each blend shape. This will allow my end users to customize the size/shape of their individual facial features while using my application. 
Here's a screen capture of the controls I'm using in DeepAR studio that I would like to have control over in the SDK:
https://www.youtube.com/watch?v=dJgawAiTnJE

Thanks for all of the awesome work you're doing!

**Comment by Sikter** [comment]
Hi there,

you should be able to do this with changeParameter methods. Take a look at this article:
https://help.deepar.ai/en/articles/3732006-changing-filter-parameters-from-code

We've done something similar in our Beauty3000 iOS app, check that out too.

Best,

Matej.

**Comment by buabbud** [comment]
Thank you Matej! Take care :)
