### ISSUE TITLE
No such module 'DeepAR'

### ISSUE THREAD

**Issue by AlexanderKozhevin** [DeepARSDK/quickstart-ios-swift#22]
<img width="1389" alt="Screenshot 2021-10-07 at 02 20 43" src="https://user-images.githubusercontent.com/4464561/136296609-2ddd2ad7-2274-4cb8-b959-e3cf300158b3.png">

<img width="1005" alt="Screenshot 2021-10-07 at 02 20 55" src="https://user-images.githubusercontent.com/4464561/136296627-7a917252-6e96-451c-8827-45c356bef5f2.png">

**Comment by bjmcallister** [comment]
What was your solution to this?

**Comment by mxnuchim** [comment]
I have this error. Happens even on a brand new project when I add the deepar package. How did you solve this?
