### ISSUE TITLE
How to implement my own camera preview?

### ISSUE THREAD

**Issue by ItsJolly** [DeepARSDK/quickstart-ios-swift#23]
I already have a camera preview working and i want to add this DeepAR over what i already have, how do i go about it? 

It says that it's in the ViewController.swift view, commented on line 90 in the Swift example.

**Comment by JelenaKB** [comment]
You can feed the frames from your camera with a custom camera controller

https://github.com/DeepARSDK/custom-cameracontroller-ios-objc

but you can't render only the AR elements over an existing view, The AR view includes both the camera image and the added 3D elements.
