### ISSUE TITLE
When app launch from background to foreground it is crashing in DeepAR SDK

### ISSUE THREAD

**Issue by bernardIos** [DeepARSDK/quickstart-ios-swift#24]
Open DeepAR camera view to record the video close the deepAR camera and put the app in background while 10-15 min and tap on app icon to open the app from background and app is crashing in deepAR SDK. I am going to share the crash report which are reported on xcode -> organizer -> crash
![Screenshot 2021-12-20 at 10 31 18 AM](https://user-images.githubusercontent.com/66058459/146714800-2cfce096-0866-4aa0-9344-7dcbccbc4d5d.png)
s

**Comment by HazemEmad** [comment]
any solutions ???

**Comment by djanekovicdeepar** [comment]
Hey everyone, I tried to reproduce this issue but unfortunately I wasn't able to do so. Could you please give me some more datapoints, namely:
- device
- ios version
- deepar version
- quickstart project commit

Also, if you have some other ways how to reproduce this, please share.

Thanks, Darko
