### ISSUE TITLE
Crash on first lauch

### ISSUE THREAD

**Issue by abinhho** [DeepARSDK/quickstart-ios-swift#25]
I got this error on first run..

```
'-[quickstart_ios_swift.ViewController didFinishShutdown]: unrecognized selector sent to instance 0x108024000'
terminating with uncaught exception of type NSException
```

Also, I could not see my license key on the dashboard. Where it is? Is it a API key?

**Comment by JelenaKB** [comment]
The fix for this issue has been pushed to the example repo
