### ISSUE TITLE
Frame Error

### ISSUE THREAD

**Issue by wanoghoco** [DeepARSDK/quickstart-ios-swift#27]
on flutter iOS(Swift) it gives the following messages 

[ViewportSizing] maximumViewportInset cannot be larger than frame
[ViewportSizing] minimumViewportInset cannot be larger than frame

and after hot reloading, the view is not rendered anymore

**Comment by JelenaKB** [comment]
Hello, we have an official flutter plugin page, if you aren't using this plugin switch to it, and if you are, can you reopen the issue on the plugin github page

https://github.com/DeepARSDK/deepar-flutter-plugin
