### ISSUE TITLE
Camera preview not working in second time present the Screen

### ISSUE THREAD

**Issue by gursewakparas** [DeepARSDK/quickstart-ios-swift#29]
https://github.com/DeepARSDK/quickstart-ios-swift/assets/48583708/64de2a35-4a1e-4030-94c9-89a8e315da7b

Camera preview not showing if i present second time to the camera recording screen.Right now i am using the testing license key.I have already purchased the basic plan but still getting same issue with paid sdk key.
Help me.

**Comment by SatvinderParas** [comment]
I am Facing the same issue in Quickstart demo as well as in my real project. Help me ASAP.


Thanks in advance.

**Comment by igor-aradski** [comment]
Hi!

Can you share more information about how you are using the DeepAR SDK? Are you initializing it on every open and shutting it on closing?

**Comment by igor-aradski** [comment]
Hi @gursewakparas @SatvinderParas!

Shutting the SDK down on closing the presented view should solve the problem.
