### ISSUE TITLE
building to simulator - ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by 8secz-johndpope** [DeepARSDK/quickstart-ios-swift#3]
arm64
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ARView", referenced from:
      objc-class-ref in ARViewController.o
     (maybe you meant: _OBJC_CLASS_$_ARViewController)
ld: symbol(s) not found for architecture x86_64

I ripped out the production sdk 
and threw in the simulator sdk 

I'm not clear how to use together - sometimes I need to build to device
right now I need to build to simulator for other things...
<img width="1713" alt="Screen Shot 2020-01-13 at 2 33 31 pm" src="https://user-images.githubusercontent.com/50567111/72231842-b2c7bd80-3611-11ea-9fac-87b84fa5ec96.png">

are there some settings to check?
above it seems embed frameworks uses sim folder
link with uses the link library....

**Comment by hdNguyenPTR** [comment]
same problem - 

ld: warning: ignoring file /Users/matt/Documents/gitWorkspace/8secondz-ios/8secondz/External/DeepAR.framework/DeepAR, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture x86_64:

**Comment by 8secz-johndpope** [comment]
I'm sure it's possible to combine the two frameworks together - not sure how though.
If not - it's fine I can work around it - instructions aren't clear though.

It seems that the two frameworks included ( one for hardware / one for simulator ) can  not / or should not be both imported - ie - if you're building  to simulator - use simulator framework / if your building to device rip out simulator and use device framework - which is what I mostly use so not a problem - but need to test something with ios13.

<img width="431" alt="Screen Shot 2020-01-20 at 11 44 32 am" src="https://user-images.githubusercontent.com/50567111/72691551-608b1d00-3b7a-11ea-82a6-e136765bb670.png">

**Comment by 8secz-johndpope** [comment]
<img width="1653" alt="Screen Shot 2020-01-29 at 9 59 19 am" src="https://user-images.githubusercontent.com/50567111/73312967-1d1d6680-427e-11ea-817b-2ea99fef980e.png">


so dropping in the simulator frameworks works a treat for dev / both on device + simulator - but not appropriate for app store.

**Comment by 8secz-johndpope** [comment]
distantly related - 


https://gist.github.com/kenthumphries/cf04683184217c7331f9c213c556c65a
https://stackoverflow.com/questions/40400086/xcode-add-embedded-binary-with-buildscript/40484337#40484337

Example_To=$BUILT_PRODUCTS_DIR"/"$PRODUCT_NAME".app/Frameworks/Example.framework/"
Example_From=$PROJECT_DIR"/../out/Build/Products/"$CONFIGURATION$EFFECTIVE_PLATFORM_NAME"/Example.framework"

mkdir -p $BUILT_PRODUCTS_DIR"/"$PRODUCT_NAME".app/Frameworks"
cp -Rv $Example_From $Example_To

if [[ $PLATFORM_NAME == 'iphoneos' ]]; then
    CODE_SIGN_IDENTITY_FOR_ITEMS="${EXPANDED_CODE_SIGN_IDENTITY_NAME}"

    if [ "${CODE_SIGN_IDENTITY_FOR_ITEMS}" = "" ] ; then
        CODE_SIGN_IDENTITY_FOR_ITEMS="${CODE_SIGN_IDENTITY}"
    fi

    codesign --force --verbose --sign "${CODE_SIGN_IDENTITY_FOR_ITEMS}" $Example_To
fi

**Comment by mauker** [comment]
I believe I went through a few steps in the right direction but even though I managed to select the right frameworks between simulator and production I still have the error

```
echo "START EMBED DEEP_AR LIB"

MY_PLATFORM_NAME=$PLATFORM_NAME
IS_SIMULATOR="iphonesimulator"

#SELECT THE CORRECT FRAMEWORK BUILT BY SIMULATOR OR NOT
if [ "$MY_PLATFORM_NAME" = "$IS_SIMULATOR" ]; then
        echo 'DEVICE SIMULADOR'
        #ADDRESS OF SIMULATOR FRAMWORK
        FRAME_WORK_CORRECT="track_white_label/Support/NotEmbedLibs/simulator/DeepAR.framework"
else
        echo 'DEVICE REAL'
        #ADDRESS OF OS FRAMWORK
        FRAME_WORK_CORRECT="track_white_label/Support/NotEmbedLibs/release/DeepAR.framework"
fi

#CREATE FOLDER TO PUT THE .framework that will be used by the application
Folder_To=$BUILT_PRODUCTS_DIR"/"$PRODUCT_NAME".app/Frameworks/DeepAR.framework/"
echo "Where to copy =>"$Folder_To
#CREATE ADRESS FROM
Folder_From=$PROJECT_DIR"/"$FRAME_WORK_CORRECT
echo "Where from copy =>"$Folder_From

#CREATE FOLDER TO PUT THE .framework that will be used by the application
mkdir -p $BUILT_PRODUCTS_DIR"/"$PRODUCT_NAME".app/Frameworks"
#COPY FILES, to aplications with space in name is needed to use an extra "" like "$Folder_To
cp -Rv $Folder_From "$Folder_To"


#GET THE IDENTTY TO SIGN
CODE_SIGN_IDENTITY_FOR_ITEMS="${EXPANDED_CODE_SIGN_IDENTITY_NAME}"

if [ "${CODE_SIGN_IDENTITY_FOR_ITEMS}" = "" ] ; then
    CODE_SIGN_IDENTITY_FOR_ITEMS="${CODE_SIGN_IDENTITY}"
fi

#CREATE A METHOD TO ASIGN
codesign_library() {
  if [ -n "${EXPANDED_CODE_SIGN_IDENTITY}" ]; then
    codesign -fs "${EXPANDED_CODE_SIGN_IDENTITY}" "$Folder_To"
  fi
}    
  
#ASSIGN IF NECESSARY
if [ "$MY_PLATFORM_NAME" != "$IS_SIMULATOR" ]; then
    codesign_library
fi

echo "FINISH EMBED DEEP_AR LIB"
```

**Comment by JelenaKB** [comment]
If you need simulator and production SDKs in the same project you could create two separate targets for them.

![Screen Shot 2021-03-15 at 18 54 36](https://user-images.githubusercontent.com/21056771/111204649-a7ca3d80-85c6-11eb-9c31-0a59763f1dbb.png)

Then you can add the frameworks only to the target that uses them and set up embedding as needed.
