### ISSUE TITLE
The camera feed does not appear the second time

### ISSUE THREAD

**Issue by Zulqurnain24** [DeepARSDK/quickstart-ios-swift#8]
The camera feed does not appear the second time the deepAR instance is accessed in the app. Please let me know how to resolve this issue. https://github.com/Zulqurnain24/DeepARSample.git

**Comment by Zulqurnain24** [comment]
I was not calling shutdown() function on deepAR instance. Once I did that the issue is resolved. Thanks to @Luka-M

**Comment by lienista** [comment]
I called the camera but it never shutdown 😥
